#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# common
cookbook 'ant'
#cookbook 'apt'
cookbook 'build-essential'
cookbook 'emacs'
#cookbook 'git'
#cookbook 'iptables'
#cookbook 'java'
#cookbook 'vim'

# ci_environment
#cookbook 'erlang'
#cookbook 'imagemagick'
#cookbook 'leiningen'
#cookbook 'memcached'
#cookbook 'mysql'
#cookbook 'openssl'
#cookbook 'python'
#cookbook 'rabbitmq'
#cookbook 'sqlite'

# worker_host
#cookbook 'chef-client'
#cookbook 'chef_handler'
#cookbook 'ntp'
#cookbook 'runit'
